version: "3.8"
services:
  app:
    image: ghcr.io/${DOCKER_IMAGE}:${GIT_COMMIT_SHA:-latest}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 6002:3000
    environment:
      - NUXT_PUBLIC_BASE_URL=https://ypod.stelmashchuk.dev
      - NUXT_PUBLIC_GIT_COMMIT_SHA=${GIT_COMMIT_SHA}
      - NUXT_YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - NUXT_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NUXT_MONGO_URI=${MONGO_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/service/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - infra_reverse-proxy
      - infra_mongo

networks:
  infra_reverse-proxy:
    external: true
  infra_mongo:
    external: true
