version: '3.8'

services:
    app:
        image: ghcr.io/${REPO_NAME}:${GIT_COMMIT_SHA:-latest}
        network_mode: 'host'
        dns:
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - '6002:3000'
        environment:
            - NUXT_PUBLIC_SECRET_FILE=/run/secrets/ypod
            - NUXT_PUBLIC_BASE_URL=${BASE_URL}
        secrets:
            - ypod
        deploy:
            update_config:
                order: start-first

secrets:
    ypod:
        external: true
